name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Build package
        run: mvn clean package --batch-mode

      - name: Run tests
        run: mvn test

      - name: Run Checkstyle (lint)
        run: mvn checkstyle:check

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: springboot-jar
          path: target/springboot-demo-0.0.1-SNAPSHOT.jar

  docker-build-push:
    needs: build-test-lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: springboot-jar
          path: target/

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: tech.sahoobasudev@gmail.com
          password: Basu#12345

      - name: Build Docker image
        run: docker build -t basutest/springboot-demo:latest .

      - name: Push Docker image
        run: docker push basutest/springboot-demo:latest

  deploy:
    needs: docker-build-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml